### ISSUE TITLE
Fullscreen with difficult exit

### ISSUE THREAD

**Issue by sim6** [caarmen/nounours-android#12]
Firstly, thanks for your work. My baby likes it very much.

Please, could you add a fullscreen mode?
Exiting from fullscreen mode should be difficult for a baby, maybe a sequence.

Thanks again.

**Comment by caarmen** [comment]
That's a great idea.  I'll look into it. Thanks :)

**Comment by sim6** [comment]
Thank you very much!

Please, could you disable home button?

**Comment by caarmen** [comment]
Thank you for your feedback.

Disabling the home button is kind of tricky.  I know some apps are able to do this completely because their app is actually a _launcher_ app: it (temporarily) replaces your home screen.  I admit the approach I took in my app is a bit more limited, but it uses the standard approach for "full screen" apps (which admittedly may not be perfect for toddlers :) )

May I ask what phone you're using, and what version of Android?  

From what I see, the full screen mode seems to work best on Android KitKat (4.4) or higher: the only way to be able to tap home on those devices is either by tapping the four corners to exit full screen mode, or by swiping from the top or bottom of the screen.  And when swiping, the home button is visible only for a few seconds.

Of course, if the device has a physical home button, I think the only way to disable it is to make the app a launcher app, which I didn't do. 

Thanks again.

**Comment by sim6** [comment]
Thanks for your detailed reply. I'm using a FairPhone1 (ASOP 4.2.2), so I have a physical button. No problem if it cannot be done, the current solution is OK. Now my baby is very happy with the phone in his hands.
Again, thanks for your efforts!
