### ISSUE TITLE
Cannot cancel theme download

### ISSUE THREAD

**Issue by snelltheta** [caarmen/nounours-android#9]
Great app, but the theme download cannot be cancelled.

**Comment by caarmen** [comment]
Indeed.  I'm currently debating (with myself) on how to solve this. 

I could make the download cancelable, but I'm afraid this might make the code quite (even more) messy...

I'm pondering removing the whole "themes on the server" part, and bundle the themes directly in the app.  No more download.  Might be simpler.  Would remove a dependency on an external resource.  Could remove a permission on the app.  All that sounds good, but the APK size will go up.  I have to make sure it won't be too big, especially since this app runs on very old devices :)

**Comment by caarmen** [comment]
I ended up making the change to bundle all the themes inside the app.  Now there is no need to download them.
There is still a non-cancelable dialog when loading a theme, but it should go faster now (as it doesn't depend on the network at all).

The apk file size went up from 761k to 2.5M.

This is included in version 2.1.0 of the app, which is currently on a staged rollout (50%) in the Play Store.

**Comment by snelltheta** [comment]
Nice. That didn't bump it up too much.
